services:
  redis:
    image: redis:7
    container_name: reachinbox-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: reachinbox-postgres
    environment:
      POSTGRES_USER: reachinbox
      POSTGRES_PASSWORD: reachinbox
      POSTGRES_DB: reachinbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
